name: monement
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.8
  hive: 2.2.3
  hive_flutter: 1.1.0
  intl:
  get: 4.6.6
  form_builder_validators: 11.0.0
  chip_list: ^3.1.0
  auto_animated: 3.2.0
  flutter_expandable_fab: 2.3.0
  fl_chart: 0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: 2.0.1
  build_runner: 2.4.12

flutter:

  uses-material-design: true